

spring:
  config:
    import: optional:classpath:application-local.yml
  application:
    name: campus-trade-server

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 1s
      timeout: 1s
#  jackson:
#    default-property-inclusion: non_null
server:
  port: 8080

logging:
  pattern:
    level: "%5p [requestId=%X{requestId:-none}]"

app:
  jwt:
    expire-seconds: ${JWT_EXPIRE_SECONDS:7200}
